const actionTypes = {
    COUNTRY_LIST_LOAD: 'COUNTRY_LIST_LOAD',
    ADD_ANSWER: 'ADD_ANSWER',
    TEMP_TYPE_CHANGE: 'TEMP_TYPE_CHANGE',
    ADD_ANSWER_FULFILLED: 'ADD_ANSWER_FULFILLED',
    COUNTRY_LIST_LOAD_FULFILLED: 'COUNTRY_LIST_LOAD_FULFILLED',
    TEMP_TYPE_CHANGE_FULFILLED: 'TEMP_TYPE_CHANGE_FULFILLED',
};

export default actionTypes;